apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: mybucket
    user: admin
    basicAuth: false
    jsonData:
      version: "Flux"
      organization: myorg
    secureJsonData:
      token: mytoken
    isDefault: true